## numpy

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


## 2D array

#### height and width

In [8]:
arr1= np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


## 3D array

In [10]:
arr2=np.array(
    [
    [[1,2,3,4],[5,6,7,8]],
    [[9,10,11,12],[13,14,15,16]],
     [[17,18,19,20],[21,22,23,24]]
    ]
              )
print(arr2)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


## Array creation using Build in mehthod
np.zeros()

np.ones()

np.full()

np.arrange()

np.linspace()

In [12]:
zarr= np.zeros((4,5))
print(zarr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
oarr=np.ones((3,6))
print(oarr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [17]:
farr=np.full((5,6), 10)
print(farr)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [20]:
import numpy as np

In [47]:
np.arange(2,100)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
range_arr=np.arange(0,100,3)

In [41]:
print(range_arr)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [51]:
larr=np.linspace(90,100)
print(larr)

[ 90.          90.20408163  90.40816327  90.6122449   90.81632653
  91.02040816  91.2244898   91.42857143  91.63265306  91.83673469
  92.04081633  92.24489796  92.44897959  92.65306122  92.85714286
  93.06122449  93.26530612  93.46938776  93.67346939  93.87755102
  94.08163265  94.28571429  94.48979592  94.69387755  94.89795918
  95.10204082  95.30612245  95.51020408  95.71428571  95.91836735
  96.12244898  96.32653061  96.53061224  96.73469388  96.93877551
  97.14285714  97.34693878  97.55102041  97.75510204  97.95918367
  98.16326531  98.36734694  98.57142857  98.7755102   98.97959184
  99.18367347  99.3877551   99.59183673  99.79591837 100.        ]


## Creating array using random number generation

np.random.rand()from 0 to 1

np.random.randn() for specific distribution

np.random.randint() from given range

In [53]:
#from 0 to 1
rand=np.random.rand(0,10) 
print(rand)

#for specific distribution
randn=np.random.randn(40,100)
print(randn) 

#from given range
randint=np.random.randint(50,70) 
print(randint)

[]
[[ 0.4688307   0.15788192  0.41044677 ... -0.5768781  -0.42367606
  -0.97654646]
 [ 0.32150075  1.02914163  0.83609336 ... -1.40782439 -1.10657857
  -1.69960077]
 [-1.650787   -0.20923512 -1.39182075 ...  1.57936041 -1.06096895
   1.37792308]
 ...
 [ 0.03167536  0.00465816 -3.52345013 ... -0.37134632  0.23650272
   0.60053425]
 [-0.55607426 -1.60626583 -1.26978371 ...  0.33376519 -0.85754547
   1.113718  ]
 [-1.60206848  0.53586489 -0.09942899 ... -0.5678656   1.0665783
  -1.12188455]]
62


## Numpy Array Attribute and Methods

### reshaping

In [56]:
x= np.array([1,2,3,4,5,6,7,8,9,10])
newarr=x.reshape(2,5) #imprtant in image filtering 
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Removing Dimensions

In [58]:
y= np.array([1,2,3,4,5,6,7,8,9,10])
y=y.reshape(-1)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


### Dimension Checking

In [61]:
a= np.array(43)
b= np.array([1,2,3,4,5])
c= np.array([[10,11,13],[14,15,16]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


## Using Ndim Creatig Dimensions

In [66]:
j= np.array([[10,11,13],[14,15,16]], ndmin=5)
print(j)
print(j.ndim)

[[[[[10 11 13]
    [14 15 16]]]]]
5


## Array Shape

In [67]:
k= np.array([[10,11,13],[14,15,16]])
print(k.shape)

(2, 3)


## Data Type of Array

In [75]:
i=np.array(["Cherry","Kiwi","Dragon Fruit"])
print(i.dtype)

s= np.array([[10,11,13],[14,15,16]], dtype='S')
print(s.dtype)

f= np.array([[10,11,13],[14,15,16]], dtype='f')
print(f.dtype)

<U12
|S2
float32


## Max AnD Min