<p align="center">
<span style="color: red;"> Name: Eman Ahmad </span> <br>
Email: <a href="emanahmad2618@gmail.com">emanahmad2618@gmail.com</a> <br>
Github: <a href="https://github.com/E32546">https://github.com/E32546</a><br>
Purpose: Numpy Practices
</p>

In [1]:
import numpy as np


In [5]:
arr=np.array([1,2,3,4,])
print(arr)

[1 2 3 4]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


# 2d array

In [13]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


# 3d array

In [14]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
zarray=np.zeros((5,6))

In [24]:
print(zarray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [50]:
onesarray=np.ones((4,4))

In [43]:
print(onesarray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
constant_array=np.full((3,7),5)

In [28]:
print(constant_array)

[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]


In [57]:
np.arange(100,2,100)


array([], dtype=int64)

In [55]:
range_arr=np.arange(0,100,2)

In [56]:
print(range_arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [37]:
linespace_arr=np.linspace(0,1,5)

In [38]:
print(linespace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [20]:
zarray=np.zeros((2,3))
onesarray=np.ones((3,4))
constant_array=np.full((2,2),4)

range_arr=np.arange(0,10,2)#start, stop, stepsize

linespace_arr=np.linspace(0,1,5)#start, stop, interval
print("zero's array= \n",zarray)
print("one's array= \n",onesarray)
print("constant_array =\n",constant_array)
print("Arrange array =\n",range_arr)
print("linespace_array=\n",linespace_arr)

zero's array= 
 [[0. 0. 0.]
 [0. 0. 0.]]
one's array= 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
constant_array =
 [[4 4]
 [4 4]]
Arrange array =
 [0 2 4 6 8]
linespace_array=
 [0.   0.25 0.5  0.75 1.  ]


## Creating array using random number generation

In [61]:
random_array=np.random.rand(5,5)

In [12]:
print("random_array")

random_array


In [63]:
normal_array=np.random.randn(2,3)

In [64]:
print(normal_array)

[[-1.08706956  0.08663866 -0.54100685]
 [-0.22598995  0.99464036  0.845318  ]]


In [80]:
randint_array=np.random.randint(2,9)

In [90]:
randint_array = np.random.randint(2, 7)



## numpy array attribute and methods

## Reshaping

In [95]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(2,5) #important in image filterring


In [8]:

print("newarr")

newarr


In [5]:
print("Hello, world!")  


Hello, world!


In [19]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(2,5) 
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Remove dimensions

In [21]:
newarr=newarr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]


## Dimension Checking

In [22]:
a=np.array(43)

In [23]:
print(a)

43


In [24]:
b=np.array([1,3,45])

In [25]:
print(b)

[ 1  3 45]


In [26]:
c=np.array([[2,4],[2,7]])

In [27]:
print(c)

[[2 4]
 [2 7]]


In [28]:
a=np.array(43)
b=np.array([1,3,45])
c=np.array([[2,4],[2,7]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


## Using ndim Creating Dimensions

In [31]:
arr=np.array([1,2,3,4,5,6,7],ndmin=10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3 4 5 6 7]]]]]]]]]]
10


# Array Shape

In [32]:
arr=np.array([[1,2,3,5,8],[7,6,4,5,6]])
print(arr.shape)

(2, 5)


## Data Type of Array


In [34]:
arr=np.array(["Apple","Banana","Cherry"])

In [35]:
print(arr)

['Apple' 'Banana' 'Cherry']


In [41]:
arr=np.array([1,2,3,4,5], dtype='S')
print(arr.dtype)
arr=np.array([1,2,3,4,5], dtype='S')
print(arr.dtype)
arr=np.array([1,2,3,4,5], dtype='f')
print(arr.dtype)


|S1
|S1
float32


## Joining

In [44]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])


In [45]:
print(arr1)

[1 2 3]


In [48]:
print(arr2)

[4 5 6]


In [49]:
arr = np.concatenate([arr1, arr2])

In [50]:
print(arr)

[1 2 3 4 5 6]


## Deleting 

In [54]:
import numpy as np

# Create an array from 0 to 9
arr1 = np.arange(10)
print(arr1)

# Delete the element at index 3
arr1 = np.delete(arr1, 3)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 4 5 6 7 8 9]


In [56]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
